using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Shared.PsycUpdate;
using Robust.Client.GameObjects;

namespace Content.Client.PsycUpdate
{
    [GenerateTypedNameReferences]
    public sealed partial class UpdateCristalSet : Control
    {
        public UpdateCristalSet(UpdateCristalSetInfo set, SpriteSystem spriteSystem)
        {
            RobustXamlLoader.Load(this);

            Icon.Texture = spriteSystem.Frame0(set.Sprite);
            SetName.Text = Loc.GetString(set.Name);
            SetDescription.Text = Loc.GetString(set.Description);
            SetButton.Text = Loc.GetString(set.Selected ? "Update-Cristal-button-deselect" : "Update-Cristal-button-select");
            SetButton.ModulateSelfOverride = set.Selected ? new Color(40, 84, 35) : new Color(68, 75, 103);
        }
    }
}
