# Tabs

- type: quickPhrase
  id: BaseCommonPhrase
  tab: Common Phrases
  abstract: true

- type: quickPhrase
  id: BaseJobPhrase
  tab: Jobs
  abstract: true

- type: quickPhrase
  id: BaseLocationPhrase
  tab: Locations
  abstract: true

- type: quickPhrase
  id: BaseSubjectPhrase
  tab: Subjects
  abstract: true

- type: quickPhrase
  id: BaseThreatPhrase
  tab: Safety
  abstract: true

- type: quickPhrase
  id: BaseSpeciesPhrase
  tab: Species
  abstract: true

# Departments

- type: quickPhrase
  id: BaseCivilianPhrase
  group: Civil
  abstract: true

- type: quickPhrase
  id: BaseCommandPhrase
  group: Comando
  styleClass: CommandButton
  abstract: true

- type: quickPhrase
  id: BaseEngineeringPhrase
  group: Engenharia
  styleClass: EngineeringButton
  abstract: true

- type: quickPhrase
  id: BaseEpistemicsPhrase
  group: Epistemics
  styleClass: EpistemicsButton
  abstract: true

- type: quickPhrase
  id: BaseJusticePhrase
  group: Justiça
  styleClass: JusticeButton
  abstract: true

- type: quickPhrase
  id: BaseLogisticsPhrase
  group: Logistica
  styleClass: LogisticsButton
  abstract: true

- type: quickPhrase
  id: BaseMedicalPhrase
  group: Medico
  styleClass: MedicalButton
  abstract: true

- type: quickPhrase
  id: BaseSecurityPhrase
  group: Segurança
  styleClass: SecurityButton
  abstract: true

- type: quickPhrase
  id: BaseServicePhrase
  group: Serviço
  styleClass: ServiceButton
  abstract: true
