using Content.Shared.Heretic.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Heretic.UI;

[GenerateTypedNameReferences]
public sealed partial class MiniHereticResearchCardControl : Control
{
    /// The technology that this control represents
    public readonly HereticResearchPrototype Research;

    public MiniHereticResearchCardControl(HereticResearchPrototype research, IPrototypeManager prototypeManager, SpriteSystem spriteSys, FormattedMessage description)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index(research.Discipline);
        Background.ModulateSelfOverride = discipline.Color;
        Texture.Texture = spriteSys.Frame0(research.Icon);
        NameLabel.SetMessage(Loc.GetString(research.Name));

        var tooltip = new Tooltip();
        tooltip.SetMessage(description);
        Main.TooltipSupplier = _ => tooltip;
        Research = research;
    }
}
