using Content.Shared.Heretic.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Heretic.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchCardControl : Control
{
    public Action? OnPressed;

    public ResearchCardControl(HereticResearchPrototype technology, IPrototypeManager prototypeManager, SpriteSystem spriteSys, FormattedMessage description, int points, bool hasAccess)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<PathPrototype>(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;

        ResearchTexture.Texture = spriteSys.Frame0(discipline.Icon);
        ResearchNameLabel.Text = Loc.GetString(technology.Name);
        var message = new FormattedMessage();
        message.AddMarkup(Loc.GetString("research-console-tier-discipline-info",
            ("tier", technology.Tier), ("color", discipline.Color), ("discipline", Loc.GetString(discipline.Name))));
        TierLabel.SetMessage(message);
        UnlocksLabel.SetMessage(description);

        ResearchTexture.Texture = spriteSys.Frame0(technology.Icon);

        if (!hasAccess)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");

        ResearchButton.Disabled = points < technology.Cost || !hasAccess;
        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
