- type: latheRecipe
  id: BorgModuleStun
  result: BorgModuleStun
  category: Weapons
  completetime: 5
  materials:
    Steel: 700
    Glass: 500
    Plastic: 200

- type: latheRecipe
  id: BorgModuleKill
  result: BorgModuleKill
  category: Weapons
  completetime: 5
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  id: BorgModuleInvestigation
  result: BorgModuleInvestigation
  category: Weapons
  completetime: 5
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850